### ISSUE TITLE
make this project pip installable

### ISSUE THREAD

**Issue by duncancfraser** [alfremedpal/PandasBasketball#1]
Love the idea behind this package, would like to leverage to do some analysis. I think I could help here if you're comfortable with my contributing. 

With a few tweaks leveraging [guidance from python.org](https://packaging.python.org/tutorials/packaging-projects/) you could take care of the requirements for the project and empower analysts to import the package, regardless of its relative path. 

Let me know if you'd be open to a contribution and I can submit a PR.

**Comment by alfremedpal** [comment]
Hey @duncancfraser ! Yes, of course I am open contributions, in fact, I encourage them. Making this project pip installable is on my to-do list, but unfortunately I have no experience on this, so any information you have is welcome. Also, there are still some features I'd like to add but I've been busy lately and I haven't had the time to keep working on PandasBasketball.

**Comment by duncancfraser** [comment]
Awesome. I have something working on a forked version of this, once I get it tightened up I'll open a PR for the pip installation!

**Comment by alfremedpal** [comment]
Great! I'm looking forward to it.

**Comment by alfremedpal** [comment]
Project is now pip-installable!

**Comment by mooneyse** [comment]
You can cross this out at the bottom of your README.md now! :smile:
